name: update
on: 
  push:
    paths:
      - "packages/dapp/**"

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for GIT_ACTIONS
        run: |
          if [ -z "${{ secrets.GIT_ACTIONS }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.GIT_ACTIONS }}

      - name: Install dependencies
        run: yarn install

      - name: Publish update
        run: eas update --auto
